### ISSUE TITLE
Rebuidl for aarch and ppc64le

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/qt-wayland-feedstock#1]

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
add
```
os_version:
  linux_64: cos7
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
build_platform:
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
```
to the config file
